name: "EffortlessHome Cloud Bridge"
version: "1.1.2"
slug: "EffortlessHome_bridge"
description: "Connects Home Assistant to the EffortlessHome Cloud WebSocket service and registers connection info"
startup: services
boot: auto
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
hassio_api: true
homeassistant_api: true
ingress: true
panel_icon: mdi:view-dashboard
panel_title: EffortlessHome Dashboard
arch:
  - amd64
  - aarch64
options:
  customer_id: ""
  system_id: ""
  ha_url: "http://homeassistant.local:8123"
  dashboard_port: 8080
schema:
  customer_id: str
  system_id: str
  ha_url: str
environment:
  TUNNEL_ORIGIN_CERT: /cert.pem
