name: "EffortlessHome Cloud"
version: 1.3.4
slug: "effortlesshome_bridge"
description: "EffortlessHome Cloud for Home Assistant with Matter Hub support"
startup: services
boot: auto
init: false
host_network: true
host_ipc: false
host_pid: false
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8080
panel_icon: "mdi:view-dashboard"
panel_title: "EffortlessHome Dashboard"
arch:
  - aarch64
  - amd64
map:
  - "config:rw"
options:
  email: ""
  password: ""
  system_id: ""
  matter_label: "favorite"
  dashboard_port: 8080
  send_on_start: true
  interval_seconds: 3600
  show_token_in_logs: false
schema:
  email: "str"
  password: "password"
  system_id: "str?"
  matter_label: "str?"
  dashboard_port: "int"
  send_on_start: "bool"
  interval_seconds: "int"
  show_token_in_logs: "bool"
environment:
  TUNNEL_ORIGIN_CERT: "/cert.pem"
privileged:
  - NET_ADMIN
  - SYS_ADMIN
