name: "EffortlessHome Cloud"
version: 1.9.1
slug: "effortlesshome_bridge"
description: "EffortlessHome Cloud for Home Assistant with Matter Hub support"
startup: services
boot: auto
init: false
host_network: true
host_ipc: false
host_pid: false
hassio_api: true
homeassistant_api: true
arch:
  - aarch64
  - amd64
map:
  - "config:rw"
options:
  email: ""
  password: ""
  matter_label: "favorite"
  send_on_start: true
  interval_seconds: 3600
  show_token_in_logs: false
schema:
  email: "str"
  password: "password"
  matter_label: "str?"
  send_on_start: "bool"
  interval_seconds: "int"
  show_token_in_logs: "bool"
environment:
  TUNNEL_ORIGIN_CERT: "/cert.pem"
privileged:
  - NET_ADMIN
  - SYS_ADMIN
